/* Generated By:JavaCC: Do not edit this line. SocialActionsParserConstants.java */
package mexica.social.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SocialActionsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 1;
  /** RegularExpression Id. */
  int SPACE = 2;
  /** RegularExpression Id. */
  int NEW_LINE = 3;
  /** RegularExpression Id. */
  int SOCIAL_ACTION = 4;
  /** RegularExpression Id. */
  int POSCONDITION = 5;
  /** RegularExpression Id. */
  int EMOTION = 6;
  /** RegularExpression Id. */
  int TENSION = 7;
  /** RegularExpression Id. */
  int TENSION_TYPE = 8;
  /** RegularExpression Id. */
  int SOCIAL_DATA = 9;
  /** RegularExpression Id. */
  int TEXT = 10;
  /** RegularExpression Id. */
  int SOCIAL_CHARACTER = 11;
  /** RegularExpression Id. */
  int SOCIAL_RELATION = 12;
  /** RegularExpression Id. */
  int SOCIAL_MODE = 13;
  /** RegularExpression Id. */
  int END_OF_FILE = 14;
  /** RegularExpression Id. */
  int SOCIAL_CHARACTER_OPT = 15;
  /** RegularExpression Id. */
  int SOCIAL_RELATION_OPT = 16;
  /** RegularExpression Id. */
  int STAR = 17;
  /** RegularExpression Id. */
  int WORD = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<SPACE>",
    "<NEW_LINE>",
    "\"ACT SOCIAL\"",
    "\"POS\"",
    "\"E\"",
    "\"T\"",
    "<TENSION_TYPE>",
    "\"SOCIAL\"",
    "\"TEXT\"",
    "\"character\"",
    "\"relation\"",
    "<SOCIAL_MODE>",
    "\"END\"",
    "<SOCIAL_CHARACTER_OPT>",
    "<SOCIAL_RELATION_OPT>",
    "\"*\"",
    "<WORD>",
    "<NUMBER>",
  };

}
