/* Generated By:JavaCC: Do not edit this line. PreviousStoriesConstants.java */
package mexica.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PreviousStoriesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int NEW_LINE = 5;
  /** RegularExpression Id. */
  int REALISED = 6;
  /** RegularExpression Id. */
  int STORY_ID = 7;
  /** RegularExpression Id. */
  int STORY_BEGIN = 8;
  /** RegularExpression Id. */
  int END_OF_FILE = 9;
  /** RegularExpression Id. */
  int SOCIAL_MARKER = 10;
  /** RegularExpression Id. */
  int NON_GENERALIZABLE_CHARACTER = 11;
  /** RegularExpression Id. */
  int RELATION_TYPE = 12;
  /** RegularExpression Id. */
  int SOCIAL_NORM_TYPE = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 3>",
    "<SPACE>",
    "<NEW_LINE>",
    "<REALISED>",
    "<STORY_ID>",
    "<STORY_BEGIN>",
    "\"END\"",
    "\"*\"",
    "<NON_GENERALIZABLE_CHARACTER>",
    "<RELATION_TYPE>",
    "<SOCIAL_NORM_TYPE>",
    "<WORD>",
    "<NUMBER>",
  };

}
