/*
 * BackgroundPanel.java
 *
 * Created on 31/07/2011, 08:40:18 PM
 */
package mexica.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import mexica.MexicaParameters;

/**
 *
 * @author Ivan Guerrero (UNAM, Mexico)
 */
public class BackgroundPanel extends javax.swing.JPanel {

    /** Creates new form BackgroundPanel */
    public BackgroundPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(337, 372));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g) {
        try {
            //BufferedImage img = ImageIO.read(BackgroundPanel.class.getClassLoader().getResource(MexicaParameters.BACKGROUND_FILE).openStream());
            BufferedImage img = ImageIO.read(new File(MexicaParameters.BACKGROUND_FILE));
            g.drawImage(img, 0, 0, Color.BLACK, null);
        } catch (IOException ex) {
            Logger.getLogger(MexicaConfiguration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
