/*
 * MexicaGUI.java
 *
 * Created on 1/07/2011, 02:26:56 PM
 */
package mexica.gui;

import javax.swing.UIManager;
import mexica.MexicaRepository;
import mexica.core.*;

/**
 *
 * @author Ivan Guerrero (UNAM, Mexico)
 */
public class MexicaActionViewer extends javax.swing.JFrame {
    private ActionStore actions;
    
    /** Creates new form MexicaGUI */
    public MexicaActionViewer() {
        initComponents();
        MexicaRepository.getInstance().loadData();
        actions = MexicaRepository.getInstance().getActions();
        
        listActions.setModel(new javax.swing.AbstractListModel() {
            
            @Override
            public int getSize() {
                return actions.getActionList().size();
            }

            @Override
            public Object getElementAt(int index) {
                Action action = actions.getActionList().get(index);
                return action;
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listActions = new javax.swing.JList();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        lblPreconditions = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPreconditions = new javax.swing.JList();
        lblPosconditions = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPosconditions = new javax.swing.JList();
        lblTensions = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTensions = new javax.swing.JList();
        lblText = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listTexts = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mexica");

        lblActions.setText("Actions:");

        listActions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listActionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listActions);

        lblName.setText("Name:");

        txtName.setText("<empty>");

        lblPreconditions.setText("Preconditions:");

        jScrollPane2.setViewportView(listPreconditions);

        lblPosconditions.setText("Posconditions:");

        jScrollPane3.setViewportView(listPosconditions);

        lblTensions.setText("Tensions:");

        jScrollPane4.setViewportView(listTensions);

        lblText.setText("Texts:");

        jScrollPane5.setViewportView(listTexts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPosconditions)
                            .addComponent(lblTensions)
                            .addComponent(lblText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreconditions)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActions)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPreconditions)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPosconditions)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTensions)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addComponent(lblText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listActionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listActionsValueChanged
        final Action action = (Action)listActions.getSelectedValue();
        txtName.setText(action.getActionName());
        listPreconditions.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() {
                return action.getPreconditions().size();
            }

            @Override
            public Object getElementAt(int index) {
                Precondition pre = action.getPreconditions().get(index);
                return (pre != null) ? pre.toString() : "N/A";
            }
        });
        listPosconditions.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() {
                return action.getPosconditions().size();
            }

            @Override
            public Object getElementAt(int index) {
                Poscondition pos = action.getPosconditions().get(index);
                return (pos != null) ? pos.toString() : "N/A";
            }
        });
        listTensions.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() {
                return action.getTensions().size();
            }

            @Override
            public Object getElementAt(int index) {
                Tension tension = action.getTensions().get(index);
                return (tension != null) ? tension.toString() : "N/A";
            }
        });
        listTexts.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() {
                return action.getTexts().size();
            }

            @Override
            public Object getElementAt(int index) {
                String text = action.getTexts().get(index);
                return text;
            }
        });
    }//GEN-LAST:event_listActionsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new MexicaActionViewer().setVisible(true);
                }
            });
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblActions;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPosconditions;
    private javax.swing.JLabel lblPreconditions;
    private javax.swing.JLabel lblTensions;
    private javax.swing.JLabel lblText;
    private javax.swing.JList listActions;
    private javax.swing.JList listPosconditions;
    private javax.swing.JList listPreconditions;
    private javax.swing.JList listTensions;
    private javax.swing.JList listTexts;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
