package mexica.gui;

import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mexica.MexicaParameters;
import mexica.reflection.TensionGraph;
import mexica.story.*;
import mexica.tools.AvatarFactory;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Ivan Guerrero (UNAM, Mexico)
 */
public class MexicaReflectionStage extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private Story story;
    
    /** Creates new form MexicaReflectionStage */
    public MexicaReflectionStage(java.awt.Frame parent, boolean modal, Story story) {
        super(parent, modal);
        this.story = story;
        this.parent = parent;
        initComponents();
        setListeners();
        setTensionGraphs();
        getContentPane().setBackground(getBackground());
        cbIllogicalActions.setSelected(MexicaParameters.ENABLE_ILLOGICAL_ACTIONS);
    }
    
    private void setListeners() {
        story.addStoryContextListener(listPendingConditions, IStoryContextListener.ListType.Conditions);
    }
    
    public void setTensionGraphs() {
        panelTensionGraphs.removeAll();
        AvatarFactory instance = story.getAvatarFactory();
        int counter = 0;
        
        for (Avatar avatar : instance.getActiveCharacters()) {
            ChartPanel panel = TensionGraph.getChart(avatar.getContext().getAvatarTensions(), story);
            panelTensionGraphs.add(panel);
            counter++;
        }
        
        for (int i=counter; i<8; i++) {
            panelTensionGraphs.add(new JPanel());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPendingConditions = new javax.swing.JLabel();
        lblTensionGraph = new javax.swing.JLabel();
        bttnSelectAction = new javax.swing.JButton();
        spGraphs = new javax.swing.JScrollPane();
        panelTensionGraphs = new javax.swing.JPanel();
        bttnAddAction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPendingConditions = new mexica.gui.JListUpdateable(story);
        cbIllogicalActions = new javax.swing.JCheckBox();

        setTitle("Reflection Stage");
        setBackground(new java.awt.Color(247, 244, 186));

        lblPendingConditions.setText("Missing Conditions");

        lblTensionGraph.setText("Tension Graphs");

        bttnSelectAction.setText("Pick an Action");
        bttnSelectAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSelectActionActionPerformed(evt);
            }
        });

        panelTensionGraphs.setMaximumSize(new java.awt.Dimension(200, 200));
        panelTensionGraphs.setMinimumSize(new java.awt.Dimension(200, 200));
        panelTensionGraphs.setPreferredSize(new java.awt.Dimension(200, 200));
        panelTensionGraphs.setLayout(new java.awt.GridLayout(2, 4));
        spGraphs.setViewportView(panelTensionGraphs);

        bttnAddAction.setText("Add Action");
        bttnAddAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddActionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listPendingConditions);

        cbIllogicalActions.setText("Enable illogical actions");
        cbIllogicalActions.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbIllogicalActionsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spGraphs, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bttnAddAction))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnSelectAction)
                                    .addComponent(cbIllogicalActions))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPendingConditions)
                            .addComponent(lblTensionGraph))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblPendingConditions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnAddAction)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnSelectAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbIllogicalActions)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTensionGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spGraphs, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnSelectActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSelectActionActionPerformed
        ConditionInstantiated cond = (ConditionInstantiated)listPendingConditions.getSelectedValue();
        if (cond != null) {
            ActionInstantiated action = cond.getAction();
            int currentYear = story.getCurrentYear();
            story.notifyPreviousAction(action);
            MexicaActionInstantiator actionInstantiator = new MexicaActionInstantiator(parent, true, action, cond, story);
            actionInstantiator.setLocationByPlatform(true);
            actionInstantiator.setVisible(true);
            setTensionGraphs();
            this.validate();
            story.setCurrentYear(currentYear);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select a condition to fulfill first", "Select a Missing Condition", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnSelectActionActionPerformed

    private void bttnAddActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddActionActionPerformed
        MexicaActionInstantiator actionInstantiator = new MexicaActionInstantiator(parent, true, story);
        actionInstantiator.setLocationByPlatform(true);
        actionInstantiator.setVisible(true);
        setTensionGraphs();
        this.validate();
    }//GEN-LAST:event_bttnAddActionActionPerformed

    private void cbIllogicalActionsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbIllogicalActionsStateChanged
        MexicaParameters.ENABLE_ILLOGICAL_ACTIONS = cbIllogicalActions.isSelected();
    }//GEN-LAST:event_cbIllogicalActionsStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAddAction;
    private javax.swing.JButton bttnSelectAction;
    private javax.swing.JCheckBox cbIllogicalActions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPendingConditions;
    private javax.swing.JLabel lblTensionGraph;
    private mexica.gui.JListUpdateable listPendingConditions;
    private javax.swing.JPanel panelTensionGraphs;
    private javax.swing.JScrollPane spGraphs;
    // End of variables declaration//GEN-END:variables
}
