/*
 * MexicaConfiguration.java
 *
 * Created on 31/07/2011, 08:25:04 PM
 */
package mexica.gui;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import mexica.CharacterName;
import mexica.MexicaParameters;
import mexica.MexicaRepository;
import mexica.action.CreateAtomsAction;
import mexica.core.Position;
import mexica.story.*;
import mexica.story.filter.StoryFilterException;
import mexica.story.log.StoryLog;
import mexica.tools.InvalidCharacterException;
import mexica.tools.PositionFactory;
import slant.MexicaAPI;
import slant.MexicaFileConfiguration;

/**
 * Main class of the project. Employed to set the basic parameters before to start the story generation process
 * @author Ivan Guerrero (UNAM, Mexico)
 */
public class MexicaConfiguration extends javax.swing.JFrame {
    private MexicaStoryGenerator storyGen;
    private boolean isEngagementMode, positionSet, actionSet, modeSet;
    private Random random;
    private Story story;
    
    /** Creates new form MexicaConfiguration */
    public MexicaConfiguration() {
        random = new Random();
        story = new Story();
        initComponents();
        cbSocialAnalysis.setSelected(false);
        loadModels();
        getContentPane().setBackground(getBackground());
        MexicaRepository.getInstance().loadData();
        cbSocialAnalysisActionPerformed(null);
    }
    
    private void loadModels() {
        storyGen = new MexicaStoryGenerator(story);
        
        lblActionSelected.setVisible(false);
        txtActionSelected.setVisible(false);
        
        listLocation.setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                 return PositionFactory.getInstance().getAvailablePositions().size();
            }

            @Override
            public Object getElementAt(int index) {
                return PositionFactory.getInstance().getAvailablePositions().get(index);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new javax.swing.ButtonGroup();
        panelBackground = new mexica.gui.BackgroundPanel();
        lblMexica = new javax.swing.JLabel();
        lblDefaultLocation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLocation = new javax.swing.JList();
        lblInitialAction = new javax.swing.JLabel();
        bttnSelectAction = new javax.swing.JButton();
        lblMode = new javax.swing.JLabel();
        radioEngagement = new javax.swing.JRadioButton();
        radioReflection = new javax.swing.JRadioButton();
        bttnStart = new javax.swing.JButton();
        lblActionSelected = new javax.swing.JLabel();
        txtActionSelected = new javax.swing.JLabel();
        lblNumberOfActions = new javax.swing.JLabel();
        lblEngagementActions = new javax.swing.JLabel();
        spEngagement = new javax.swing.JSpinner();
        lblACASII = new javax.swing.JLabel();
        spACAS = new javax.swing.JSpinner();
        lblSimilarityPercentage = new javax.swing.JLabel();
        bttnRandomLocation = new javax.swing.JButton();
        lblStoryActions = new javax.swing.JLabel();
        spStoryActions = new javax.swing.JSpinner();
        bttnRandomAction = new javax.swing.JButton();
        lblReflectionActions = new javax.swing.JLabel();
        spReflection = new javax.swing.JSpinner();
        socialPanel = new javax.swing.JPanel();
        lblSocialACAS = new javax.swing.JLabel();
        spSocialACAS = new javax.swing.JSpinner();
        lblSpecialNorms = new javax.swing.JLabel();
        cbSpecialNorms = new javax.swing.JCheckBox();
        lblACAS = new javax.swing.JLabel();
        lblACASIII = new javax.swing.JLabel();
        spACASII = new javax.swing.JSpinner();
        spACASIII = new javax.swing.JSpinner();
        cbSocialAnalysis = new javax.swing.JCheckBox();
        lblMexicaSocial = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mexicaMenu = new javax.swing.JMenu();
        loadDataMenu = new javax.swing.JMenuItem();
        socialAnalyzerMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configure Mexica");
        setBackground(new java.awt.Color(250, 245, 245));
        setLocationByPlatform(true);
        setResizable(false);

        panelBackground.setBackground(java.awt.SystemColor.controlDkShadow);
        panelBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblMexica.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        lblMexica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMexica.setText("Mexica");

        lblDefaultLocation.setText("Select the default starting location for your characters:");

        listLocation.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listLocation.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listLocationValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listLocation);

        lblInitialAction.setText("Select an action to start with:");

        bttnSelectAction.setText("Select Action");
        bttnSelectAction.setActionCommand("");
        bttnSelectAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSelectActionActionPerformed(evt);
            }
        });

        lblMode.setText("Select a mode to start with:");

        radioEngagement.setBackground(getBackground());
        modeGroup.add(radioEngagement);
        radioEngagement.setSelected(true);
        radioEngagement.setText("Engagement Mode");
        radioEngagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEngagementActionPerformed(evt);
            }
        });

        radioReflection.setBackground(getBackground());
        modeGroup.add(radioReflection);
        radioReflection.setText("Reflection Mode");
        radioReflection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioReflectionActionPerformed(evt);
            }
        });

        bttnStart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttnStart.setText("Start");
        bttnStart.setToolTipText("Start creating your own story!");
        bttnStart.setEnabled(false);
        bttnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnStartActionPerformed(evt);
            }
        });

        lblActionSelected.setText("Action selected:");

        txtActionSelected.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtActionSelected.setText("<Select>");
        txtActionSelected.setMaximumSize(new java.awt.Dimension(180, 14));
        txtActionSelected.setPreferredSize(new java.awt.Dimension(180, 14));

        lblNumberOfActions.setText("Number of actions to generate:");

        lblEngagementActions.setLabelFor(spEngagement);
        lblEngagementActions.setText("Engagement Mode:");

        spEngagement.setModel(new javax.swing.SpinnerNumberModel(3, 1, 10, 1));

        lblACASII.setText("ACAS II percentage:");

        spACAS.setModel(new javax.swing.SpinnerNumberModel(50, 0, 100, 5));

        lblSimilarityPercentage.setText("Similarity Percentage:");

        bttnRandomLocation.setText("Random pick");
        bttnRandomLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRandomLocationActionPerformed(evt);
            }
        });

        lblStoryActions.setLabelFor(spStoryActions);
        lblStoryActions.setText("Story:");

        spStoryActions.setModel(new javax.swing.SpinnerNumberModel(15, 1, 50, 1));

        bttnRandomAction.setText("Random action");
        bttnRandomAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRandomActionActionPerformed(evt);
            }
        });

        lblReflectionActions.setLabelFor(spReflection);
        lblReflectionActions.setText("Reflection Mode:");

        spReflection.setModel(new javax.swing.SpinnerNumberModel(10, 1, 50, 1));

        socialPanel.setBackground(new java.awt.Color(250, 245, 245));

        lblSocialACAS.setText("Social ACAS percentage:");

        spSocialACAS.setModel(new javax.swing.SpinnerNumberModel(80, 0, 100, 5));

        lblSpecialNorms.setText("Enable special social norms:");

        cbSpecialNorms.setSelected(true);
        cbSpecialNorms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpecialNormsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout socialPanelLayout = new javax.swing.GroupLayout(socialPanel);
        socialPanel.setLayout(socialPanelLayout);
        socialPanelLayout.setHorizontalGroup(
            socialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socialPanelLayout.createSequentialGroup()
                .addGroup(socialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(socialPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblSocialACAS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(spSocialACAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(socialPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSpecialNorms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(cbSpecialNorms)))
                .addContainerGap())
        );
        socialPanelLayout.setVerticalGroup(
            socialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socialPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(socialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialACAS)
                    .addComponent(spSocialACAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(socialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSpecialNorms)
                    .addComponent(lblSpecialNorms))
                .addContainerGap())
        );

        lblACAS.setText("ACAS percentage:");

        lblACASIII.setText("ACAS III percentage:");

        spACASII.setModel(new javax.swing.SpinnerNumberModel(50, 0, 100, 5));

        spACASIII.setModel(new javax.swing.SpinnerNumberModel(50, 0, 100, 5));

        cbSocialAnalysis.setSelected(true);
        cbSocialAnalysis.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        cbSocialAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSocialAnalysisActionPerformed(evt);
            }
        });

        lblMexicaSocial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMexicaSocial.setText("Social Norms in Mexica");

        mexicaMenu.setText("Mexica");

        loadDataMenu.setAction(new CreateAtomsAction());
        loadDataMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadDataMenu.setText("Load data");
        mexicaMenu.add(loadDataMenu);

        socialAnalyzerMenu.setText("Launch social analyzer");
        socialAnalyzerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialAnalyzerMenuActionPerformed(evt);
            }
        });
        mexicaMenu.add(socialAnalyzerMenu);

        jMenuBar1.add(mexicaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMexica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDefaultLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblActionSelected)
                                                .addComponent(lblInitialAction)
                                                .addComponent(lblMode)
                                                .addComponent(lblNumberOfActions))
                                            .addGap(35, 35, 35))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblEngagementActions)
                                                .addComponent(lblReflectionActions)
                                                .addComponent(lblStoryActions))
                                            .addGap(60, 60, 60)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(radioReflection, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioEngagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bttnSelectAction)
                                        .addComponent(spEngagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spReflection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spStoryActions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(bttnStart)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(socialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblACASIII, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblACASII, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblACAS, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spACASIII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spACAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spACASII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbSocialAnalysis))
                                        .addGap(23, 23, 23)))
                                .addGap(0, 0, 0))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bttnRandomAction)
                                            .addComponent(bttnRandomLocation)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMexicaSocial)
                                            .addComponent(lblSimilarityPercentage))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(txtActionSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblMexica)
                .addGap(18, 18, 18)
                .addComponent(lblDefaultLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnRandomLocation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInitialAction)
                    .addComponent(bttnSelectAction)
                    .addComponent(bttnRandomAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActionSelected)
                    .addComponent(txtActionSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEngagement)
                    .addComponent(lblMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioReflection)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberOfActions, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSimilarityPercentage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEngagementActions, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spACAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblACAS)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spReflection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReflectionActions)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblACASII)
                                    .addComponent(spACASII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblACASIII)
                            .addComponent(spACASIII, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMexicaSocial)
                            .addComponent(spStoryActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStoryActions)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbSocialAnalysis)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 65, Short.MAX_VALUE)
                        .addComponent(bttnStart))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addComponent(socialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        lblACASIII.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnSelectActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSelectActionActionPerformed
        if (story.getDefaultPosition() != Position.NotDefined) {
            MexicaActionInstantiator actionGUI = new MexicaActionInstantiator(this, true, story);
            actionGUI.setLocationByPlatform(true);
            actionGUI.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Please select a default position first", "Select a Default Position", JOptionPane.ERROR_MESSAGE);

        if (story.getActions().size() > 0) {
            showSelectedAction();
        }
        else {
            lblActionSelected.setVisible(false);
            txtActionSelected.setVisible(false);
            actionSet = false;
        }
        
        validateStart();
    }//GEN-LAST:event_bttnSelectActionActionPerformed

    private void bttnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnStartActionPerformed
        setConfigValues();
        StoryLog.addMessage(story, "Initial action: " + story.getActions().get(0));
        StoryLog.addMessage(story, "Default location: " + story.getDefaultPosition().name());
        //Establishes the mode to start
        //Allows view the frame maximized
        //storyGen.setExtendedState(storyGen.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        storyGen.setLocationByPlatform(true);
        storyGen.setMode(isEngagementMode);
        storyGen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnStartActionPerformed

    private void listLocationValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listLocationValueChanged
        if (listLocation.getSelectedIndex() >= 0) {
            story.setDefaultPosition((Position)listLocation.getSelectedValue());
            positionSet = true;
        }
        else {
            positionSet = false;
        }
        
        validateStart();
    }//GEN-LAST:event_listLocationValueChanged

    private void radioEngagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEngagementActionPerformed
        isEngagementMode = true;
        modeSet = true;
        validateStart();
    }//GEN-LAST:event_radioEngagementActionPerformed

    private void radioReflectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioReflectionActionPerformed
        isEngagementMode = false;
        modeSet = true;
        validateStart();
    }//GEN-LAST:event_radioReflectionActionPerformed

    private void bttnRandomLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRandomLocationActionPerformed
        int index = listLocation.getModel().getSize();
        listLocation.setSelectedIndex(random.nextInt(index));
    }//GEN-LAST:event_bttnRandomLocationActionPerformed

    private void bttnRandomActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRandomActionActionPerformed
        ActionInstantiated action = MexicaAPI.obtainRandomAction(story, false);
        
        try {
            int option = JOptionPane.showConfirmDialog(this, action.toString(), "Add action to story?", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                story.restart(true, true);
                story.addAction(action.getAction(), action.getCharactersList().toArray(new CharacterName[0]));
                showSelectedAction();
            }
        } catch (InvalidCharacterException | DeadAvatarException | StoryFilterException ex) {
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnRandomActionActionPerformed

    private void cbSocialAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSocialAnalysisActionPerformed
        socialPanel.setVisible(cbSocialAnalysis.isSelected());
        MexicaParameters.ENABLE_SOCIAL_ANALYSIS = cbSocialAnalysis.isSelected();
    }//GEN-LAST:event_cbSocialAnalysisActionPerformed

    private void socialAnalyzerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialAnalyzerMenuActionPerformed
        setConfigValues();
        StorySocialAnalyzerGUI socialAnalyzer = new StorySocialAnalyzerGUI(this, false);
        socialAnalyzer.setLocationRelativeTo(this);
        socialAnalyzer.setVisible(true);
    }//GEN-LAST:event_socialAnalyzerMenuActionPerformed

    private void cbSpecialNormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpecialNormsActionPerformed
        MexicaParameters.ENABLE_SPECIAL_SOCIAL_NORMS = cbSpecialNorms.isSelected();
    }//GEN-LAST:event_cbSpecialNormsActionPerformed

    private void validateStart() {
        bttnStart.setEnabled(actionSet && positionSet && modeSet);
    }
    
    private void showSelectedAction() {
        lblActionSelected.setVisible(true);
        txtActionSelected.setVisible(true);

        String action = story.getActions().get(0).toString();
        txtActionSelected.setText(action);
        actionSet = true;
    }
    
    private void setConfigValues() throws NumberFormatException {
        //Sets the number of actions to be generated on each cycle
        MexicaParameters.MAX_ENGAGEMENT_ACTIONS = Integer.parseInt(spEngagement.getValue().toString());
        MexicaParameters.MAX_REFLECTION_ACTIONS = Integer.parseInt(spReflection.getValue().toString());
        MexicaParameters.MAX_ACTIONS_IN_STORY = Integer.parseInt(spStoryActions.getValue().toString());
        MexicaParameters.ACAS_CONSTANT = Integer.parseInt(spACAS.getValue().toString());
        MexicaParameters.ACAS_II_CONSTANT = Integer.parseInt(spACASII.getValue().toString());
        MexicaParameters.ACAS_III_CONSTANT = Integer.parseInt(spACASIII.getValue().toString());
        MexicaParameters.INITIAL_STATE = isEngagementMode;
        MexicaParameters.ENABLE_SOCIAL_ANALYSIS = cbSocialAnalysis.isSelected();
        if (MexicaParameters.ENABLE_SOCIAL_ANALYSIS) {
            MexicaParameters.SOCIAL_ACAS_CONSTANT = Integer.parseInt(spSocialACAS.getValue().toString());
            MexicaParameters.ENABLE_SPECIAL_SOCIAL_NORMS = cbSpecialNorms.isSelected();
        }
        MexicaParameters.DISPLAY_GRAPHICAL_NOTIFICATIONS = true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    if (MexicaParameters.ENABLE_LOG_INFO)
                        Logger.getGlobal().setLevel(Level.INFO);
                    else
                        Logger.getGlobal().setLevel(Level.OFF);
                    MexicaFileConfiguration fileConfig = new MexicaFileConfiguration();
                    try {
                        fileConfig.loadConfiguration();
                        MexicaConfiguration config = new MexicaConfiguration();
                        config.setLocationByPlatform(true);
                        config.setVisible(true);
                    } catch (IOException ioe) {}
                }
            });
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnRandomAction;
    private javax.swing.JButton bttnRandomLocation;
    private javax.swing.JButton bttnSelectAction;
    private javax.swing.JButton bttnStart;
    private javax.swing.JCheckBox cbSocialAnalysis;
    private javax.swing.JCheckBox cbSpecialNorms;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblACAS;
    private javax.swing.JLabel lblACASII;
    private javax.swing.JLabel lblACASIII;
    private javax.swing.JLabel lblActionSelected;
    private javax.swing.JLabel lblDefaultLocation;
    private javax.swing.JLabel lblEngagementActions;
    private javax.swing.JLabel lblInitialAction;
    private javax.swing.JLabel lblMexica;
    private javax.swing.JLabel lblMexicaSocial;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblNumberOfActions;
    private javax.swing.JLabel lblReflectionActions;
    private javax.swing.JLabel lblSimilarityPercentage;
    private javax.swing.JLabel lblSocialACAS;
    private javax.swing.JLabel lblSpecialNorms;
    private javax.swing.JLabel lblStoryActions;
    private javax.swing.JList listLocation;
    private javax.swing.JMenuItem loadDataMenu;
    private javax.swing.JMenu mexicaMenu;
    private javax.swing.ButtonGroup modeGroup;
    private mexica.gui.BackgroundPanel panelBackground;
    private javax.swing.JRadioButton radioEngagement;
    private javax.swing.JRadioButton radioReflection;
    private javax.swing.JMenuItem socialAnalyzerMenu;
    private javax.swing.JPanel socialPanel;
    private javax.swing.JSpinner spACAS;
    private javax.swing.JSpinner spACASII;
    private javax.swing.JSpinner spACASIII;
    private javax.swing.JSpinner spEngagement;
    private javax.swing.JSpinner spReflection;
    private javax.swing.JSpinner spSocialACAS;
    private javax.swing.JSpinner spStoryActions;
    private javax.swing.JLabel txtActionSelected;
    // End of variables declaration//GEN-END:variables
}