/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrevStoriesAnalyzer.java
 *
 * Created on 6/11/2011, 06:52:21 PM
 */
package mexica.gui;

import java.awt.event.KeyEvent;
import javax.swing.table.*;
import mexica.story.analyzer.PrevStory;
import mexica.story.analyzer.PrevStoryAvatar;
import mexica.story.analyzer.PrevStoryParser;

/**
 *
 * @author Ivan Guerrero (UNAM, Mexico)
 */
public class PrevStoriesAnalyzer extends javax.swing.JFrame {

    /** Creates new form PrevStoriesAnalyzer */
    public PrevStoriesAnalyzer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrevStory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrevStory = new javax.swing.JTextArea();
        lblCharacters = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCharacters = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Previous Stories Analyzer");

        lblPrevStory.setText("Previous Story:");

        txtPrevStory.setColumns(20);
        txtPrevStory.setRows(5);
        txtPrevStory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrevStoryKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtPrevStory);

        lblCharacters.setText("Characters:");

        tblCharacters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "# Actions Performed", "# Actions Received", "# Tensions Performed", "# Tensions Received", "# Actions", "# Tensions", "Last action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCharacters);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(lblPrevStory)
                    .addComponent(lblCharacters)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrevStory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCharacters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrevStoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrevStoryKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PrevStoryParser.getInstance().parse(txtPrevStory.getText());
            PrevStory prevStory = PrevStoryParser.getInstance().getPrevStory();
            DefaultTableModel myModel = (DefaultTableModel)tblCharacters.getModel();
            for (int i=0; i<myModel.getRowCount();) {
                myModel.removeRow(0);
            }
            for (PrevStoryAvatar avatar : prevStory.getAvatars()) {
                myModel.addRow(new Object[] {avatar.getName(), avatar.getActionsPerformed(), avatar.getActionsReceived(),
                                             avatar.getTensionsPerformed(), avatar.getTensionsReceived(), 
                                             avatar.getTotalActions(), avatar.getTotalTensions(), avatar.getLastActionNumber()});
            }
            tblCharacters.setModel(myModel);
        }
    }//GEN-LAST:event_txtPrevStoryKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new PrevStoriesAnalyzer().setVisible(true);
                }
            });
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCharacters;
    private javax.swing.JLabel lblPrevStory;
    private javax.swing.JTable tblCharacters;
    private javax.swing.JTextArea txtPrevStory;
    // End of variables declaration//GEN-END:variables
}
