package mexica.action.gui;

import javax.swing.*;
import mexica.MexicaParameters;
import mexica.core.*;

/**
 *
 * @author ivang_000
 */
public class EmotionPanel extends javax.swing.JPanel {
    private Condition condition;
    /**
     * Creates new form EmotionPanel
     */
    public EmotionPanel() {
        initComponents();
        loadEmotions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbEmotionType = new javax.swing.JComboBox<EmotionType>();
        jLabel2 = new javax.swing.JLabel();
        spIntensity = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        cbPerformer = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbReceiver = new javax.swing.JComboBox();
        cbProportionalIntensity = new javax.swing.JCheckBox();
        cbPresenceConditioned = new javax.swing.JCheckBox();

        jLabel1.setText("Emotion type:");

        jLabel2.setText("Intensity:");

        spIntensity.setModel(new javax.swing.SpinnerNumberModel(0, -3, 3, 1));

        jLabel3.setText("Performer:");

        cbPerformer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "La", "Lb", "any" }));

        jLabel4.setText("Receiver:");

        cbReceiver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b", "La", "Lb", "any", "" }));

        cbProportionalIntensity.setText("%");
        cbProportionalIntensity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbProportionalIntensityStateChanged(evt);
            }
        });

        cbPresenceConditioned.setText("Presence conditioned");
        cbPresenceConditioned.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cbPresenceConditioned.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbEmotionType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPerformer, 0, 100, Short.MAX_VALUE)
                                .addComponent(cbReceiver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbProportionalIntensity))))
                    .addComponent(cbPresenceConditioned))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbEmotionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spIntensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProportionalIntensity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPerformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cbPresenceConditioned)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbProportionalIntensityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbProportionalIntensityStateChanged
        spIntensity.setEnabled(!cbProportionalIntensity.isSelected());
    }//GEN-LAST:event_cbProportionalIntensityStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<EmotionType> cbEmotionType;
    private javax.swing.JComboBox cbPerformer;
    private javax.swing.JCheckBox cbPresenceConditioned;
    private javax.swing.JCheckBox cbProportionalIntensity;
    private javax.swing.JComboBox cbReceiver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spIntensity;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the condition
     */
    public Condition getCondition() {
        if (condition == null)
            condition = new Condition();
        condition.setConditionType(ConditionType.Emotion);
        condition.setEmotionType((EmotionType)cbEmotionType.getSelectedItem());
        if (cbProportionalIntensity.isSelected())
            condition.setIntensity(MexicaParameters.PROPORTIONAL_INTENSITY);
        else
            condition.setIntensity((int)spIntensity.getValue());
        condition.setCharacterA((String)cbPerformer.getSelectedItem());
        //If the selected value is empty space, do not store anything
        if (cbReceiver.getSelectedIndex() < cbReceiver.getModel().getSize() - 1)
            condition.setCharacterB((String)cbReceiver.getSelectedItem());
        condition.setPresenceConditioned(cbPresenceConditioned.isSelected());
        return condition;
    }

    /**
     * @param condition the condition to set
     */
    public void setCondition(Condition condition) {
        this.condition = condition;
        if (condition != null) {
            cbEmotionType.setSelectedItem(condition.getEmotion());
            if (condition.getIntensity() == MexicaParameters.PROPORTIONAL_INTENSITY)
                cbProportionalIntensity.setSelected(true);
            else
                spIntensity.setValue(condition.getIntensity());
            cbPerformer.setSelectedItem(condition.getCharacterA());
            if (condition.getCharacterB() != null)
                cbReceiver.setSelectedItem(condition.getCharacterB());
            else
                cbReceiver.setSelectedIndex(cbReceiver.getModel().getSize()-1);
            cbPresenceConditioned.setSelected(condition.isPresenceConditionedTension());
        }
    }

    private void loadEmotions() {
        DefaultComboBoxModel<EmotionType> model = new DefaultComboBoxModel<>();
        for (EmotionType e : EmotionType.values()) {
            model.addElement(e);
        }
        cbEmotionType.setModel(model);
    }
}
