package mexica.action.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import mexica.MexicaParameters;
import mexica.MexicaRepository;
import mexica.core.*;
import mexica.reflection.ActionsWriter;

/**
 * Class to manage the available actions for Mexica.
 * @author ivang_000
 */
public class MexicaActionManagerGUI extends javax.swing.JDialog {

    /**
     * Creates new form MexicaActionManagerGUI
     * @param parent
     * @param modal
     */
    public MexicaActionManagerGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbActions = new javax.swing.JList<Action>();
        jLabel2 = new javax.swing.JLabel();
        panelDetails = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtActionName = new javax.swing.JTextField();
        spNoCharacters = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbPreconditions = new javax.swing.JList<Condition>();
        bttnAddPrecondition = new javax.swing.JButton();
        bttnEditPrecondition = new javax.swing.JButton();
        bttnDeletePrecondition = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbPosconditions = new javax.swing.JList<Condition>();
        bttnAddPoscondition = new javax.swing.JButton();
        bttnEditPoscondition = new javax.swing.JButton();
        bttnDeletePoscondition = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lbTexts = new javax.swing.JList<String>();
        bttnAddText = new javax.swing.JButton();
        bttnEditText = new javax.swing.JButton();
        bttnDeleteText = new javax.swing.JButton();
        bttnNewAction = new javax.swing.JButton();
        bttnSaveAction = new javax.swing.JButton();
        bttnDeleteAction = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSaveActions = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Action Manager");

        jLabel1.setText("Actions:");

        lbActions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lbActions.setToolTipText("");
        lbActions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbActionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbActions);

        jLabel2.setText("Details:");

        jLabel3.setText("Action name:");

        jLabel4.setText("Number of characters:");

        jLabel5.setText("Preconditions:");

        spNoCharacters.setModel(new javax.swing.SpinnerNumberModel(2, 0, 2, 1));

        jScrollPane2.setViewportView(lbPreconditions);

        bttnAddPrecondition.setText("Add");
        bttnAddPrecondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnAddPrecondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnAddPrecondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnAddPrecondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddPreconditionActionPerformed(evt);
            }
        });

        bttnEditPrecondition.setText("Edit");
        bttnEditPrecondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnEditPrecondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnEditPrecondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnEditPrecondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditPreconditionActionPerformed(evt);
            }
        });

        bttnDeletePrecondition.setText("Delete");
        bttnDeletePrecondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnDeletePrecondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnDeletePrecondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnDeletePrecondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeletePreconditionActionPerformed(evt);
            }
        });

        jLabel6.setText("Posconditions:");

        jScrollPane3.setViewportView(lbPosconditions);

        bttnAddPoscondition.setText("Add");
        bttnAddPoscondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnAddPoscondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnAddPoscondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnAddPoscondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddPosconditionActionPerformed(evt);
            }
        });

        bttnEditPoscondition.setText("Edit");
        bttnEditPoscondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnEditPoscondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnEditPoscondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnEditPoscondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditPosconditionActionPerformed(evt);
            }
        });

        bttnDeletePoscondition.setText("Delete");
        bttnDeletePoscondition.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnDeletePoscondition.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnDeletePoscondition.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnDeletePoscondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeletePosconditionActionPerformed(evt);
            }
        });

        jLabel7.setText("Preferred text:");

        jScrollPane5.setViewportView(lbTexts);

        bttnAddText.setText("Add");
        bttnAddText.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnAddText.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnAddText.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnAddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddTextActionPerformed(evt);
            }
        });

        bttnEditText.setText("Edit");
        bttnEditText.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnEditText.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnEditText.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEditTextActionPerformed(evt);
            }
        });

        bttnDeleteText.setText("Delete");
        bttnDeleteText.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnDeleteText.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnDeleteText.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnDeleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62)
                        .addComponent(txtActionName))
                    .addGroup(panelDetailsLayout.createSequentialGroup()
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(panelDetailsLayout.createSequentialGroup()
                                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetailsLayout.createSequentialGroup()
                                        .addComponent(bttnAddPoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnEditPoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnDeletePoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spNoCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDetailsLayout.createSequentialGroup()
                                        .addComponent(bttnAddPrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnEditPrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnDeletePrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnDeleteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtActionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spNoCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAddPrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnEditPrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnDeletePrecondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAddPoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnEditPoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnDeletePoscondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnAddText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnDeleteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bttnNewAction.setText("New");
        bttnNewAction.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnNewAction.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnNewAction.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnNewAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNewActionActionPerformed(evt);
            }
        });

        bttnSaveAction.setText("Save");
        bttnSaveAction.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnSaveAction.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnSaveAction.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnSaveAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSaveActionActionPerformed(evt);
            }
        });

        bttnDeleteAction.setText("Delete");
        bttnDeleteAction.setMaximumSize(new java.awt.Dimension(65, 23));
        bttnDeleteAction.setMinimumSize(new java.awt.Dimension(65, 23));
        bttnDeleteAction.setPreferredSize(new java.awt.Dimension(65, 23));
        bttnDeleteAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menuSaveActions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSaveActions.setText("Save actions to file");
        menuSaveActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionsActionPerformed(evt);
            }
        });
        jMenu1.add(menuSaveActions);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnNewAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnDeleteAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnSaveAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnNewAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnSaveAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnDeleteAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbActionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbActionsValueChanged
        Action action = lbActions.getSelectedValue();
        if (action != null) {
            txtActionName.setText(action.getActionName());
            spNoCharacters.setValue(action.getNoCharacters());
            DefaultListModel<Condition> model = new DefaultListModel<>();
            for (Condition c : action.getPreconditions()) {
                model.addElement(c);
            }
            lbPreconditions.setModel(model);
            lbPreconditions.validate();

            model = new DefaultListModel<>();
            for (Condition c : action.getPosconditions()) {
                model.addElement(c);
            }
            for (Condition c : action.getTensions()) {
                model.addElement(c);
            }
            lbPosconditions.setModel(model);
            lbPosconditions.validate();

            DefaultListModel<String> textModel = new DefaultListModel<>();
            for (String s : action.getTexts()) {
                textModel.addElement(s);
            }
            lbTexts.setModel(textModel);
            lbTexts.validate();
        }
        else {
            clearForm();
        }
    }//GEN-LAST:event_lbActionsValueChanged

    private void bttnAddPreconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddPreconditionActionPerformed
        ConditionManagerGUI gui = new ConditionManagerGUI(null, true);
        gui.setVisible(true);
        Condition condition = gui.getCondition();
        if (condition != null) {
            DefaultListModel<Condition> model = (DefaultListModel<Condition>)lbPreconditions.getModel();
            model.addElement(condition);
        }
    }//GEN-LAST:event_bttnAddPreconditionActionPerformed

    private void bttnAddPosconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddPosconditionActionPerformed
        ConditionManagerGUI gui = new ConditionManagerGUI(null, true);
        gui.setVisible(true);
        Condition condition = gui.getCondition();
        if (condition != null) {
            DefaultListModel<Condition> model = (DefaultListModel<Condition>)lbPosconditions.getModel();
            model.addElement(condition);
        }
    }//GEN-LAST:event_bttnAddPosconditionActionPerformed

    private void bttnNewActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNewActionActionPerformed
        Action action = new Action();
        action.setActionName("new action");
        DefaultListModel<Action> model = (DefaultListModel<Action>)lbActions.getModel();
        model.addElement(action);
        lbActions.setSelectedValue(action, true);
    }//GEN-LAST:event_bttnNewActionActionPerformed

    private void bttnSaveActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSaveActionActionPerformed
        Action action = lbActions.getSelectedValue();
        readForm(action);
        lbActions.validate();
        clearForm();
    }//GEN-LAST:event_bttnSaveActionActionPerformed

    private void bttnEditPreconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditPreconditionActionPerformed
        Condition condition = lbPreconditions.getSelectedValue();
        ConditionManagerGUI gui = new ConditionManagerGUI(null, true);
        gui.setCondition(condition);
        gui.setVisible(true);
        lbPreconditions.revalidate();
    }//GEN-LAST:event_bttnEditPreconditionActionPerformed

    private void bttnEditPosconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditPosconditionActionPerformed
        Condition condition = lbPosconditions.getSelectedValue();
        ConditionManagerGUI gui = new ConditionManagerGUI(null, true);
        gui.setCondition(condition);
        gui.setVisible(true);
        lbPosconditions.revalidate();
    }//GEN-LAST:event_bttnEditPosconditionActionPerformed

    private void bttnDeleteActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionActionPerformed
        Action action = lbActions.getSelectedValue();
        if (action != null) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove the action " + action.getActionName(), 
                    "Delete action", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                DefaultListModel<Action> model = (DefaultListModel<Action>)lbActions.getModel();
                model.removeElement(action);
                lbActions.revalidate();
            }
        }
    }//GEN-LAST:event_bttnDeleteActionActionPerformed

    private void bttnDeletePreconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeletePreconditionActionPerformed
        removeSelectedValue(lbPreconditions, "precondition");
    }//GEN-LAST:event_bttnDeletePreconditionActionPerformed

    private void bttnDeletePosconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeletePosconditionActionPerformed
        removeSelectedValue(lbPosconditions, "poscondition");
    }//GEN-LAST:event_bttnDeletePosconditionActionPerformed

    private void menuSaveActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionsActionPerformed
        ActionsWriter writer = new ActionsWriter(MexicaParameters.ACTIONS_FILE);
        try {
            writer.write((DefaultListModel<Action>)lbActions.getModel());
            JOptionPane.showMessageDialog(null, "Actions saved in " + MexicaParameters.ACTIONS_FILE, "Actions", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "There were problems while storing the actions", "Error saving actions", JOptionPane.ERROR_MESSAGE);
            Logger.getGlobal().log(Level.WARNING, ioe.getMessage());
        }
    }//GEN-LAST:event_menuSaveActionsActionPerformed

    private void bttnEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEditTextActionPerformed
        String text = lbTexts.getSelectedValue();
        DefaultListModel<String> model = (DefaultListModel<String>)lbTexts.getModel();
        text = JOptionPane.showInputDialog(this, "Write down a new text for the action", text);
        int index = lbTexts.getSelectedIndex();
        model.remove(index);
        model.insertElementAt(text, index);
        lbTexts.updateUI();
    }//GEN-LAST:event_bttnEditTextActionPerformed

    private void bttnAddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddTextActionPerformed
        String text = JOptionPane.showInputDialog(this, "Write down a new text for the action");
        DefaultListModel<String> model = (DefaultListModel<String>)lbTexts.getModel();
        model.addElement(text);
        lbTexts.updateUI();
    }//GEN-LAST:event_bttnAddTextActionPerformed

    private void bttnDeleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteTextActionPerformed
        DefaultListModel<String> model = (DefaultListModel<String>)lbTexts.getModel();
        model.remove(lbTexts.getSelectedIndex());
        lbTexts.updateUI();
    }//GEN-LAST:event_bttnDeleteTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MexicaActionManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MexicaActionManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MexicaActionManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MexicaActionManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MexicaActionManagerGUI dialog = new MexicaActionManagerGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAddPoscondition;
    private javax.swing.JButton bttnAddPrecondition;
    private javax.swing.JButton bttnAddText;
    private javax.swing.JButton bttnDeleteAction;
    private javax.swing.JButton bttnDeletePoscondition;
    private javax.swing.JButton bttnDeletePrecondition;
    private javax.swing.JButton bttnDeleteText;
    private javax.swing.JButton bttnEditPoscondition;
    private javax.swing.JButton bttnEditPrecondition;
    private javax.swing.JButton bttnEditText;
    private javax.swing.JButton bttnNewAction;
    private javax.swing.JButton bttnSaveAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<Action> lbActions;
    private javax.swing.JList<Condition> lbPosconditions;
    private javax.swing.JList<Condition> lbPreconditions;
    private javax.swing.JList<String> lbTexts;
    private javax.swing.JMenuItem menuSaveActions;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JSpinner spNoCharacters;
    private javax.swing.JTextField txtActionName;
    // End of variables declaration//GEN-END:variables

    private void loadActions() {
        MexicaRepository repo = MexicaRepository.getInstance();
        if (repo.getActions() == null)
            repo.loadData();
        ActionStore store = repo.getActions();
        DefaultListModel<Action> model = new DefaultListModel<>();
        for (Action act : store.getActionList()) {
            model.addElement(act);
        }
        lbActions.setModel(model);
        lbActions.validate();
    }

    private void clearForm() {
        txtActionName.setText("");
        spNoCharacters.setValue(2);
        DefaultListModel<Condition> model = (DefaultListModel)lbPreconditions.getModel();
        model.clear();
        lbPreconditions.validate();

        model = (DefaultListModel)lbPosconditions.getModel();
        model.clear();
        lbPosconditions.validate();

        DefaultListModel<String> textModel = (DefaultListModel)lbTexts.getModel();
        textModel.clear();
        lbTexts.validate();
    }
    
    private Action readForm(Action action) {
        action.setActionName(txtActionName.getText().replaceAll("\\s+", "_"));
        action.setNoCharacters((int)spNoCharacters.getValue());
        
        DefaultListModel<Condition> model = (DefaultListModel<Condition>)lbPreconditions.getModel();
        for (int i=0; i<model.size(); i++) {
            Condition c = model.elementAt(i);
            Precondition p = new Precondition();
            p.setConditionType(c.getConditionType());
            p.setEmotionType(c.getEmotion());
            p.setTensionType(c.getTension());
            p.setIntensity(c.getIntensity());
            p.setCharacterA(c.getCharacterA());
            p.setCharacterB(c.getCharacterB());
            action.addPrecondition(p);
        }
        
        model = (DefaultListModel<Condition>)lbPosconditions.getModel();
        for (int i=0; i<model.size(); i++) {
            Condition c = model.elementAt(i);
            Condition p = null;
            switch (c.getConditionType()) {
                case Emotion:
                    p = new Poscondition();
                    p.setConditionType(ConditionType.Emotion);
                    p.setCharacterA(c.getCharacterA());
                    p.setCharacterB(c.getCharacterB());
                    p.setConditionType(c.getConditionType());
                    p.setEmotionType(c.getEmotion());
                    p.setIntensity(c.getIntensity());
                    action.addPoscondition((Poscondition)p);
                    break;
                case Tension:
                    p = new Tension();
                    p.setConditionType(ConditionType.Tension);
                    p.setCharacterA(c.getCharacterA());
                    p.setCharacterB(c.getCharacterB());
                    p.setTensionType(c.getTension());
                    action.addTension((Tension)p);
                    break;
            }            
        }
        
        action.getTexts().clear();
        DefaultListModel<String> textModel = (DefaultListModel<String>)lbTexts.getModel();
        for (int i=0; i<textModel.size(); i++) {
            String text = textModel.elementAt(i);
            action.addText(text);
        }
        
        return action;
    }

    private void removeSelectedValue(JList<Condition> list, String title) {
        Condition condition = list.getSelectedValue();
        if (condition != null) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove the " + title + " " + condition, 
                    "Delete " + title, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                DefaultListModel<Condition> model = (DefaultListModel<Condition>)list.getModel();
                model.removeElement(condition);
                list.revalidate();
            }
        }
    }
}